#define y(F,Q,K,x,c,G,W,u,o,S,t,L,h,N,p,z,m,Y) D(m,G,Y,z,o,p,W,u,h),D(K,F,t,S,Q,L,N,x,c),U(J(t,Y),J(x,u),J(c,h),J(Q,o),J(K,m),J(S,z),J(N,W),J(F,G),J(L,p))
#define g10 1
#define R01 0
#define R(x,r) H(R,x,r)
#define g00 0
#define D(V,L,r,F,z,S,h,G,u) J(J(J(J(J(J(J(C(r,G,u),C(F,S,L)),C(h,z,V)),C(r,F,h)),C(G,S,z)),C(u,L,V)),C(r,S,V)),C(u,S,h))
#define J(p,j) H(g,p,j)
#define H(x,Y,j) v(x,Y,j)
#define g01 1
#define g11 1
#define v(o,r,p) o##r##p
#define R11 1
#define C(o,b,z) R(R(z,b),o)
#define R00 0
#define U(z,N,d,L,a,u,x,r,o) C(C(d,N,z),C(r,o,u),C(a,L,x))
#define R10 0
